name: GitHub Pages deploy

on:
  push:
    branches:
      - release
      - temp-nish
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Build & push Docker image
        uses: docker/build-push-action@v4
        with:
          context: "."
          file: "deployment/Dockerfile"
          push: true
          tags: "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.run_id }}"
          cache-from: type=gha
          cache-to: type=gha,mode=max,ignore-error=true